server:
  port: 8081
  servlet:
    path: /crud-example

spring:
  profiles:
    active:
    - develop

# Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
# H2 
  h2:
    console:
      enabled: true
      path: /h2    